name: Deploy Nginx website

on:
  push:
    branches:
      - main

jobs:
  deploy:  # fixed typo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Engine
        uses: docker/setup-docker@v2
        with:
          version: 20.10.24

      - name: Build docker image
        run: docker build -t my-nginx-website .  # fixed lowercase docker

      - name: Run docker container
        run: |
          docker stop nginx-container || true
          docker rm nginx-container || true
          docker run -d -p 80:80 --name nginx-container my-ng
