name: Deploy Nginx website

on:
  push:
    branches:
      - main

jobs:
  deplou:
    runs-on: ubuntu:latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: Docker build -t my-nginx-website .

      - name: run docker container
        run:
          docker stop nginx-container || true
          docker rm nginx-container || true
          docker run -d -p 80:80 --name nginx-container my-nginx-website
